//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PathologyEntities : DbContext
    {
        public PathologyEntities()
            : base("name=PathologyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBL_CONSULTANT> TBL_CONSULTANT { get; set; }
        public virtual DbSet<TBL_R_CAT> TBL_R_CAT { get; set; }
        public virtual DbSet<TBL_R_DEPT> TBL_R_DEPT { get; set; }
        public virtual DbSet<TBL_R_PATIENT> TBL_R_PATIENT { get; set; }
        public virtual DbSet<TBL_R_RECEIPT> TBL_R_RECEIPT { get; set; }
        public virtual DbSet<TBL_R_TEST> TBL_R_TEST { get; set; }
        public virtual DbSet<TBL_USER_D> TBL_USER_D { get; set; }
        public virtual DbSet<View_Visit> View_Visit { get; set; }
    }
}
